language: go

go:
  - 1.x

sudo: false

install:
  - go get gitlab.com/Ma_124/awesome-framework/cmd/awesome

before_script:
  - $GOPATH/bin/awesome version

script:
  - $GOPATH/bin/awesome internal -githubci

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable or as an encrypted variable (see ma124.js.org/s/travis_var)
  keep-history: true
  local-dir: public
  on:
    branch: master

